### PR TITLE
feat: allow escalation events in Camunda 8.2

### PR DESCRIPTION
**Pull request by barmac**
Related to https://github.com/camunda/camunda-modeler/issues/3318

### CODE REVIEW

**Comment by barmac** [comment]
This is now ready for review.

**Comment by barmac** [comment]
I removed the `no-expression` part completely. In C8, either escalation is disallowed at all or we can type expressions wherever the properties panel supports it.

**Comment by barmac** [comment]
On the other hand, the engine won't allow `=myCode` as a static escalation code:

```
Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'escalation-test.bpmn': - Element: BoundaryEventDefinition
    - ERROR: The escalationCode of the escalation catch event is not allowed to be an expression
- Element: StartEventDefinition
    - ERROR: The escalationCode of the escalation catch event is not allowed to be an expression
 [ deploy-error ]
```

**Comment by barmac** [comment]
Ready for review.

**Review by philippfromme — APPROVED** [review]
Works on my machine! ✅

**Pull request merged**
