### PR TITLE
Allow Blank Error Catch Event in Camunda 8.2

### PR DESCRIPTION
**Pull request by philippfromme**
Conflicting events in scope will be implemented separately.

---

Related to https://github.com/camunda/camunda-modeler/issues/3362

### CODE REVIEW

**Comment by barmac** [comment]
We need to add a rule that there can be only one catch-all error start event in the scope.

**Comment by philippfromme** [comment]
@koevskinikola confirmed that there can only be one catch-all start event in a scope. So we'll implement this.

**Comment by philippfromme** [comment]
@barmac @mars @nikku Ready for review.

**Comment by barmac** [comment]
Looking into this today.

**Comment by barmac** [comment]
Sorry, I totally missed this. Will review at most tomorrow.

**Comment by barmac** [comment]
I am wondering whether the scope thing is actually a Camunda 8 concern or rather a general BPMN compliance concern. Note that this plugin may become a bag of all rules.

Also, note that the "single catch-all event per scope" is not only about error events, but can also apply to escalation events. Therefore, it may make sense to extract it from error-reference rule to a general one.

**Comment by nikku** [comment]
> I am wondering whether the scope thing is actually a Camunda 8 concern or rather a general BPMN compliance concern. Note that this plugin may become a bag of all rules.

Great find. Only one "interrupting" per scope is a general BPMN concern. Does it make sense to split up the rule then?

**Comment by philippfromme** [comment]
> Does it make sense to split up the rule then?

I'm looking into this.

**Comment by philippfromme** [comment]
@nikku Not sure if we can move this to [bpmnlint](https://github.com/bpmn-io/bpmnlint) as this is dependent on an engine version (Camunda 8.2 allows it). We might just keep it in this plugin for now.

As far as I understand, this rule can be generalized to errors and escalations (not to messages), so the behavior would be:

catch-all

@barmac @nikku Please confirm.

**Comment by barmac** [comment]
My suggestion is: Implement the rule in bpmnlint only. This is not a problem of compatibility with the engine, but a general BPMN standard incompatibility. So this plugin should be about preventing the deployment failure for engine-related reasons.

Regarding your diagram, it looks correct to me.

**Comment by nikku** [comment]
Diagram looks good.

**Comment by nikku** [comment]
The thing you'd move to bpmnlint is the fact that multiple conflicting canceling event subscriptions are an anti-pattern.

**Comment by philippfromme** [comment]
@barmac @nikku After discussing the issue with @nikku, I decided to keep the pull request focused on the error code. Conflicting events in scope will be implemented separately.

**Review by barmac — APPROVED** [review]

**Pull request merged**
