### PR TITLE
feat(rule): add secrets rule

### PR DESCRIPTION
**Pull request by Oleksiivanov**
Added secrets rule.

required secrets format : `{{secrets.SECRET_WORD}}`
secrets can be in <zeebe:properties>, <zeebe:ioMapping> and in <zeebe:subscription>

result : 
```
  Activity_0gcnr68  error  Element of type <zeebe:input> contains an invalid secret format in property 'body'. Must be {{secrets.YOUR_SECRET}}                               camunda-compat/secrets              
  StartEvent_1      error  Element of type <zeebe:property> contains an invalid secret format in property 'activationCondition'. Must be {{secrets.YOUR_SECRET}}             camunda-compat/secrets              
  Event_0hdo39k     error  Element of type <zeebe:property> contains an invalid secret format in property 'inbound.responseBodyExpression'. Must be {{secrets.YOUR_SECRET}}  camunda-compat/secrets              
  Message_0pier1w   error  Element of type <zeebe:subscription> contains an invalid secret format in property 'correlationKey'. Must be {{secrets.YOUR_SECRET}}              3741e070-ac1a-4bca-8936-dc04dca5c408

```

Related : https://github.com/camunda/team-connectors/issues/448

### CODE REVIEW

**Comment by philippfromme** [comment]
@Oleksiivanov Just to clarify, this rule should be active for Camunda 8.0 and newer only, right?

**Comment by philippfromme** [comment]
@Oleksiivanov I've refactored the implementation to align with our existing code base. Feel free to have a look.

Just to clarify, we want to validate _only_ the following properties:

* `zeebe:Input#source`
* `zeebe:Property#value`
* `zeebe:Subscription#correlationKey`

Correct? Is there a plan to add more in the future?

**Comment by philippfromme** [comment]
> > 
> 
> Thank you @philippfromme . it's correct, but i have a little confusion, I tested code also in terminal: `bpmnlint testDiagramWithErrors.bpmn`, and it didn't work with upper letter in the property field like here : `zeebe:Input`, but worked with small ` zeebe:input`, and now, I see that you commit works for tests, but it doesn't work for test diagram from the terminal, is this expected situation?

It should only work for uppercase because the types are in it. I'll look into it.

**Comment by philippfromme** [comment]
> > @Oleksiivanov Just to clarify, this rule should be active for Camunda 8.0 and newer only, right?

So deploying to Camunda 8.0 will result in the secrets getting validated by the engine or the connectors runtime? Can you help me understand?

**Comment by philippfromme** [comment]
How exactly did you test using the command line?

**Comment by philippfromme** [comment]
Another question: How do secrets work in FEEL expressions? Since you can't use ``{{}}` the pattern won't match, right?

**Review by igpetrov — APPROVED** [review]
LGTM but I am not familiar with JS best practices.

I am relying here on experts' opinion.

**Comment by philippfromme** [comment]
That merge shouldn't have happened. I don't think we need to revert but we will look into why this merge happened.

**Comment by nikku** [comment]
Let's revert + restore this PR so we can review + ship in an orderly manner.

**Comment by nikku** [comment]
@Oleksiivanov Could you create a follow-up PR to re-add the changes. I restored your `secrets` branch? It is best to clarify all open points before merging this.

**Comment by nikku** [comment]
Thanks @Oleksiivanov. Let's follow-up via #119 once @philippfromme is back from FTO.

**Pull request merged**
