### PR TITLE
Allow signal boundary events, signal catch events, signal start events in subprocess

### PR DESCRIPTION
**Pull request by smbea**
Related to https://github.com/camunda/camunda-modeler/issues/3819

### CODE REVIEW

**Review by barmac — CHANGES_REQUESTED** [review]
In the light of https://github.com/camunda/camunda-modeler/issues/3819#issuecomment-1701174639, there's no need for `signal-catch-with-incoming-event-gateway` rule. Camunda 8.3 will allow any signal catch events.

**Comment by smbea** [comment]
> In the light of [camunda/camunda-modeler#3819 (comment)](https://github.com/camunda/camunda-modeler/issues/3819#issuecomment-1701174639), there's no need for `signal-catch-with-incoming-event-gateway` rule. Camunda 8.3 will allow any signal catch events.

I completely missed that 🤦‍♀️ I'll rework this

**Comment by smbea** [comment]
That test is testing the `no-signal-event-sub-process` rule against 8.3. But in reality, that rule is not included for 8.3: https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/135/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R58. And that aspect is already tested: https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/135/files#diff-c0edd0e1987ebf4144374c735ff8166e5624a9eebe543aa6bae70659a5db86feL220

**Comment by smbea** [comment]
@barmac do you agree we can drop that test?

**Review by barmac — APPROVED** [review]
You're right, there is no need for this test. I removed the commit, and let's merge this :rocket:

**Pull request merged**
