### PR TITLE
feat: add rule disallowing loops

### PR DESCRIPTION
**Pull request by philippfromme**
Disallows loops according to https://github.com/camunda/zeebe/pull/13025.

The algorithm works as follows:

1. Find all elements that can be part of a loop
2. For each of them, try and find a loop
3. Report an error once the first loop has been found

### Loop on a single process level

no-loop-errors

### Nested loop on a single process level

no-loop-errors-4

### Loop on multiple process levels

no-loop-errors-3

### Loop with call activity

no-loop-errors-5

### Ignored loop

no-loop-errors-2

---

Closes https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/100

### CODE REVIEW

**Review by nikku — APPROVED** [review]
Looks good. What complexity does this algorithm have (with respect to the number of flow elements per process)? And hence, what is the run-time cost for [a larger diagram](https://demo.bpmn.io/s/application-processing).

**Comment by philippfromme** [comment]
Oh no, I wasn't done with this, hence I hadn't assigned anyone. 🙈 Anyway, the handling of call activities was missing. Here's a follow-up pull request: https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/130

**Comment by philippfromme** [comment]
> What complexity does this algorithm have (with respect to the number of flow elements per process)? And hence, what is the run-time cost for [a larger diagram](https://demo.bpmn.io/s/application-processing).

Let me figure this out.

**Comment by nikku** [comment]
> https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/102#issuecomment-1701015301

You can create a PR as a draft if you want to signal that it is not ready (yet).

**Comment by philippfromme** [comment]
> You can create a PR as a draft if you want to signal that it is not ready (yet).

I know, you reviewed within the shot timespan between marking it as ready and pushing the final commit. 😅

**Comment by nikku** [comment]
Great results. Good thing is that rule execution is async, that means that overall interaction is not blocking.

**Pull request merged**
