### PR TITLE
chore: rename cloud 1.4 to 8.0

### PR DESCRIPTION
**Pull request by smbea**
Related to https://github.com/camunda/camunda-modeler/issues/2736

### CODE REVIEW

**Review by MaxTru — APPROVED** [review]
:wave:

**Comment by philippfromme** [comment]
@MaxTru Isn't the name supposed to be `camunda-platform-8-0` instead of `camunda-cloud-8-0`?

**Comment by smbea** [comment]
> @MaxTru Isn't the name supposed to be `camunda-platform-8-0` instead of `camunda-cloud-8-0`?

In this stage we would only change "cloud" in display labels and text, not technical attributes. So behind the scenes the modeler will still work with "Cloud" but display it as "Platform 8".

I will still change the linting messages from "Not compatible with Camunda Cloud x" to Platform 8.x and Zeebe 1.0-1.3 as part of the [renaming issue](https://github.com/camunda/camunda-modeler-design/issues/76). But internally, it remains cloud.

But correct me if I'm wrong @MaxTru

**Comment by MaxTru** [comment]
Exactly. So technicall it is: Camunda Platform and Camunda Cloud. UI-wise it is: Camunda Platform 8.x and Camunda Platform 7.x.

I considered the file name `camunda-xxx-8.0` as the `technical` descriptor for us internally.

**Comment by philippfromme** [comment]
Okay, thanks for clarifying. 👍🏻

**Pull request merged**
